# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from contracts import search_pb2 as contracts_dot_search__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contracts/search_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChunkSearchStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchChunks = channel.unary_unary(
                '/search.ChunkSearch/SearchChunks',
                request_serializer=contracts_dot_search__pb2.SearchChunksRequest.SerializeToString,
                response_deserializer=contracts_dot_search__pb2.SearchChunksResponse.FromString,
                _registered_method=True)


class ChunkSearchServicer:
    """Missing associated documentation comment in .proto file."""

    def SearchChunks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChunkSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchChunks': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchChunks,
                    request_deserializer=contracts_dot_search__pb2.SearchChunksRequest.FromString,
                    response_serializer=contracts_dot_search__pb2.SearchChunksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search.ChunkSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('search.ChunkSearch', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChunkSearch:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SearchChunks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/search.ChunkSearch/SearchChunks',
            contracts_dot_search__pb2.SearchChunksRequest.SerializeToString,
            contracts_dot_search__pb2.SearchChunksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
