syntax = "proto3";

package search;

service ChunkSearch {
  rpc SearchChunks(SearchChunksRequest) returns (SearchChunksResponse);
  rpc SearchChunksFts(SearchChunksFtsRequest) returns (SearchChunksFtsResponse);
  rpc RerankChunks(RerankChunksRequest) returns (RerankChunksResponse);
}

message SearchChunksRequest {
  string question = 1;
  uint32 limit = 2;
}

message Chunk {
  int64 document_id = 1;
  string document_number = 2;
  int32 chunk_number = 3;
  string content = 4;
  double distance = 5;
}

message SearchChunksResponse {
  repeated Chunk chunks = 1;
}

message SearchChunksFtsRequest {
  string question = 1;
  uint32 limit = 2;
}

message FtsChunk {
  int64 document_id = 1;
  string document_number = 2;
  int32 chunk_number = 3;
  string content = 4;
  double rank = 5;
}

message SearchChunksFtsResponse {
  repeated FtsChunk chunks = 1;
}

message RerankChunksRequest {
  string question = 1;
}

message RerankedChunk {
  int64 document_id = 1;
  string document_number = 2;
  int32 chunk_number = 3;
  string content = 4;
  double distance = 5;
  double reranker_score = 6;
}

message RerankChunksResponse {
  repeated RerankedChunk chunks = 1;
}
